# Generated by Django 4.1.5 on 2023-08-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('portada', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('nro_seguidores', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('anio_lanzamiento', models.CharField(max_length=4)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.FloatField()),
                ('audio', models.CharField(max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='canciones_album', to='nospeak_app.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='canciones_playlist', to='nospeak_app.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('fecha_expiracion', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suscripciones', to='nospeak_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recomendacion', models.DateField()),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='canciones_recomendacion', to='nospeak_app.cancion')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='playlist_recomendacion', to='nospeak_app.playlist')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recomendaciones_usuario', to='nospeak_app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='playlists_usuario', to='nospeak_app.usuario'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateField()),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='canciones_historial', to='nospeak_app.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historiales', to='nospeak_app.usuario')),
            ],
        ),
    ]
